import "@/assets/styles/globals.css";
import { Inter } from 'next/font/google'
import { APP_NAME } from "@/lib/constants";
const inter = Inter({ subsets: ['latin'] })
import { ThemeProvider } from "next-themes";
import { Metadata } from "next";

export const metadata = {
  title: `${APP_NAME}`,
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} flex justify-center`} suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={true}
          disableTransitionOnChange={true}
        >
          <div className="w-[95vw] md:w-[90vw] lg:w-[1068px]">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
